sim/mahasiswa/routes.py
import imp
from random import random
import re
from flask import Flask, render_template, redirect, request, url_for, Blueprint, flash, request
from sim.mahasiswa.forms import editsurat_F, mahasiswa_F, loginmahasiswa_F, editmahasiswa_F, pengaduan_F, editpengaduan_F, surat_F
from sim.models import Tmahasiswa, Tpengaduan, Tpendataansurat
from sim import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
import os
import secrets
from sim import app
from PIL import Image


rmahasiswa = Blueprint('rmahasiswa', __name__)


    #simpan foto
def simpan_foto(form_foto):
    random_hex= secrets.token_hex(8)
    f_name, f_ext= os.path.splitext(form_foto.filename)
    foto_fn=random_hex + f_ext
    foto_path= os.path.join(app.root_path, 'sim/static/foto', foto_fn)
    ubah_size=(300,300)
    j=Image.open(form_foto)
    j.thumbnail(ubah_size)
    j.save(foto_path)
    #form_foto.save(foto_path)
    return foto_fn

@rmahasiswa.route("/")
def home():
    return render_template("home.html")


@rmahasiswa.route("/about")
def about():
    return render_template("about.html")


@rmahasiswa.route("/data_mahasiswa", methods=['GET', 'POST'])
def data_mhswa():
    form = mahasiswa_F()
    if form.validate_on_submit():
        pass_hash=bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        add_mahasiswa = Tmahasiswa(npm=form.npm.data, nama=form.nama.data, email=form.email.data,
                                   password=pass_hash, kelas=form.kelas.data, alamat=form.alamat.data)
        db.session.add(add_mahasiswa)
        db.session.commit()
        flash(f'Akun- {form.npm.data} berhasil daftar', 'info')
        return redirect(url_for('rmahasiswa.login_mahasiswa'))
    return render_template("data-mahasiswa.html", form=form)


@rmahasiswa.route("/login_mahasiswa", methods=['GET', 'POST'])
def login_mahasiswa():
    if current_user.is_authenticated:
        return redirect(url_for('rmahasiswa.home'))
    form = loginmahasiswa_F()
    if form.validate_on_submit():
        ceknpm= Tmahasiswa.query.filter_by(npm=form.npm.data).first()
        if ceknpm and bcrypt.check_password_hash(ceknpm.password, form.password.data):
            login_user(ceknpm)
            flash('Selamat Datang Kembali', 'warning')
            return redirect(url_for('rmahasiswa.akunmahasiswa'))
        else:
            flash('Login Gagal, Periksa NPM dan Password kembali!', 'danger')
    return render_template("login_mahasiswa.html", form=form)


@rmahasiswa.route("/akunmahasiswa")
@login_required
def akunmahasiswa():
    return render_template('akunmahasiswa.html')


@rmahasiswa.route("/logout_mahasiswa")
def logout_mahasiswa():
    logout_user()
    return redirect(url_for('rmahasiswa.home'))





@rmahasiswa.route("/edit_mahasiswa", methods=['GET', 'POST'])
@login_required
def edit_mahasiswa():
    form=editmahasiswa_F()
    if form.validate_on_submit():
        if form.foto.data:
            file_foto=simpan_foto(form.foto.data)
            current_user.foto = file_foto
        pass_hash=bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        current_user.nama=form.nama.data
        current_user.npm=form.npm.data
        current_user.email=form.email.data
        current_user.kelas=form.kelas.data
        current_user.alamat=form.alamat.data
        current_user.password=pass_hash
        db.session.commit()
        flash('Data Berhasil di Ubah','warning')
        return redirect(url_for('rmahasiswa.edit_mahasiswa'))
    elif request.method=="GET":
        form.nama.data=current_user.nama
        form.npm.data=current_user.npm
        form.email.data=current_user.email
        form.kelas.data=current_user.kelas
        form.alamat.data=current_user.alamat
    return render_template("edit_mahasiswa.html", form=form )


@rmahasiswa.route("/pengaduan", methods=['GET', 'POST'])
@login_required
def pengaduan():
    dt_pengaduan=Tpengaduan.query.filter_by(mahasiswa_id=current_user.id)
    form=pengaduan_F()
    if form.validate_on_submit():
        #tambah data pengaduan
        add_pengaduan= Tpengaduan(subjek=form.subjek.data, kategori=form.kategori.data, detail_pengaduan=form.detail_pengaduan.data, mahasiswa=current_user)
        db.session.add(add_pengaduan)
        db.session.commit()
        flash('Data Berhasil di Tambahkan','warning')
        return redirect(url_for('rmahasiswa.pengaduan'))
    return render_template('pengaduan.html', form=form, dt_pengaduan=dt_pengaduan)


@rmahasiswa.route("/pengaduan/<int:ed_id>/update", methods=['GET', 'POST'])
@login_required
def update_pengaduan(ed_id):
    form=editpengaduan_F()
    dt_pengaduan=Tpengaduan.query.get_or_404(ed_id)
    if request.method=="GET":
        form.subjek.data=dt_pengaduan.subjek
        form.kategori.data=dt_pengaduan.kategori
        form.detail_pengaduan.data=dt_pengaduan.detail_pengaduan

    elif form.validate_on_submit():
        dt_pengaduan.subjek=form.subjek.data
        dt_pengaduan.kategori=form.kategori.data
        dt_pengaduan.detail_pengaduan=form.detail_pengaduan.data
        db.session.commit()
        flash('Data Berhasil di Ubah', 'warning')
        return redirect(url_for('rmahasiswa.pengaduan'))
    return render_template('edit_pengaduan.html', form=form)

@rmahasiswa.route("/delete/<id>", methods=['GET', 'POST'])
@login_required
def hapus_pengaduan(id):
    h_pengaduan=Tpengaduan.query.get(id)
    db.session.delete(h_pengaduan)
    db.session.commit()
    flash('Data Berhasil di Hapus', 'warning')
    return redirect(url_for('rmahasiswa.pengaduan'))


@rmahasiswa.route("/pengaduan/<int:ed_id>/detail", methods=['GET', 'POST'])
@login_required
def detail_pengaduan(ed_id):
    dt_pengaduan=Tpengaduan.query.get_or_404(ed_id)
    return render_template('detail_pengaduan.html', dt_pengaduan=dt_pengaduan)


#surat

@rmahasiswa.route("/pendataansurat", methods=['GET', 'POST'])
@login_required
def pendataansurat():
    dt_pendataansurat=Tpendataansurat.query.filter_by(mahasiswaid=current_user.id)
    form=surat_F()
    if form.validate_on_submit():
        #tambah data pengaduan
        add_pendataansurat= Tpendataansurat(nomor_surat=form.nomor_surat.data, jenis_surat=form.jenis_surat.data, perihal=form.perihal.data, sifat_surat=form.sifat_surat.data, nama_instansi=form.nama_instansi.data, pmahasiswa=current_user)
        db.session.add(add_pendataansurat)
        db.session.commit()
        flash('Data Berhasil di Tambahkan','warning')
        return redirect(url_for('rmahasiswa.pendataansurat'))
    return render_template('pendataansurat.html', form=form, dt_pendataansurat=dt_pendataansurat)

#edit
@rmahasiswa.route("/pendataansurat/<int:ed_id>/update", methods=['GET', 'POST'])
@login_required
def update_pendataansurat(ed_id):
    form=editsurat_F()
    dt_pendataansurat=Tpendataansurat.query.get_or_404(ed_id)
    if request.method=="GET":
        form.nomor_surat.data=dt_pendataansurat.nomor_surat
        form.jenis_surat.data=dt_pendataansurat.jenis_surat
        form.perihal.data=dt_pendataansurat.perihal
        form.sifat_surat.data=dt_pendataansurat.sifat_surat
        form.nama_instansi.data=dt_pendataansurat.nama_instansi


    elif form.validate_on_submit():
        dt_pendataansurat.nomor_surat=form.nomor_surat.data
        dt_pendataansurat.jenis_surat=form.jenis_surat.data
        dt_pendataansurat.perihal=form.perihal.data
        dt_pendataansurat.sifat_surat=form.sifat_surat.data
        dt_pendataansurat.nama_instansi=form.nama_instansi.data
        db.session.commit()
        flash('Data Berhasil di Ubah', 'warning')
        return redirect(url_for('rmahasiswa.pendataansurat'))
    return render_template('edit_surat.html', form=form)

#hapus
@rmahasiswa.route("/deletep/<id>", methods=['GET', 'POST'])
@login_required
def hapus_pendataansurat(id):
    h_pendataansurat=Tpendataansurat.query.get(id)
    db.session.delete(h_pendataansurat)
    db.session.commit()
    flash('Data Berhasil di Hapus', 'warning')
    return redirect(url_for('rmahasiswa.pendataansurat'))

@rmahasiswa.route("/pendataansurat/<int:ed_id>/detail", methods=['GET', 'POST'])
@login_required
def detail_surat(ed_id):
    dt_pendataansurat=Tpendataansurat.query.get_or_404(ed_id)
    return render_template('detail_surat.html', dt_pendataansurat=dt_pendataansurat)

@rmahasiswa.route("/artikel")
def artikel_info(info):
    return render_template("artikel.html")

sim/templates/about.html
{% extends "base.html" %}

{% block konten%}

<h1>Tentang kami</h1>
<p>Flask adalah sebuah web framework yang ditulis dengan bahasa Python dan tergolong sebagai jenis microframework. Flask
    berfungsi sebagai kerangka kerja aplikasi dan tampilan dari suatu web. Dengan menggunakan Flask dan bahasa Python,
    pengembang dapat membuat sebuah web yang terstruktur dan dapat mengatur behaviour suatu web dengan lebih mudah.
    Flask termasuk pada jenis microframework karena tidak memerlukan suatu alat atau pustaka tertentu dalam
    penggunaannya. Sebagian besar fungsi dan komponen umum seperti validasi form, database, dan sebagainya tidak
    terpasang secara default di Flask. Hal ini dikarenakan fungsi dan komponen-komponen tersebut sudah disediakan oleh
    pihak ketiga dan Flask dapat menggunakan ekstensi yang membuat fitur dan komponen-komponen tersebut seakan
    diimplementasikan oleh Flask sendiri. Selain itu, meskipun Flask disebut sebagai microframework, bukan berarti Flask
    mempunyai kekurangan dalam hal fungsionalitas. Microframework disini berarti bahwa Flask bermaksud untuk membuat
    core dari aplikasi ini sesederhana mungkin tapi tetap dapat dengan mudah ditambahkan. Dengan begitu, fleksibilitas
    serta skalabilitas dari Flask dapat dikatakan cukup tinggi dibandingkan dengan framework lainnya.</p>

{% endblock %}

sim/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Watchline</title>
    <link href="{{ url_for ('static', filename='css/bootstrap.min.css')}}" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for ('static', filename='css/style.css')}}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
        <div class="container">
            <div class="container-fluid">
                <a class="navbar-brand fs-2" href="#">Watchline</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                    aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarScroll">
                    <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                        <li class="nav-item fs-5">
                            <a class="nav-link active" aria-current="page"
                                href="{{url_for('rmahasiswa.home')}}">Home</a>
                        </li>
                        <li class="nav-item fs-5">
                            <a class="nav-link" href="{{url_for('rmahasiswa.about')}}">About</a>
                        </li>
                        {% if current_user.is_authenticated %}

                        {% else %}
                        <li class="nav-item fs-5">
                            <a class="nav-link" href="{{url_for('rmahasiswa.login_mahasiswa')}}">Login Mahasiswa</a>
                        </li>
                        {% endif %}
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
    </nav>

    <div class="container mt-4">
        <div class="row">
            <div class="col-md-8">
                <div class="shadow p-3 mb-5 bg-white rounded">
                    <!--flash-->
                    {% with messages= get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                    {% for category, message in messages %}

                    <div class="alert alert-{{category}}">
                        {{message}}
                    </div>
                    {% endfor %}
                    {% endif %}
                    {% endwith %}



                    {%block konten%}

                    {%endblock%}
                </div>
            </div>
            <div class="col-md-4">
                <div class="shadow p-3 mb-5 bg-white rounded">
                    {% if current_user.is_authenticated %}
                    <div class="card" style="width: 24rem;">
                        <img src="{{url_for('static', filename='foto/' + current_user.foto)}}" class="card-img-top"
                            alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{current_user.nama}}</h5>
                            <p class="card-text">{{current_user.email}}.</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"><a href="{{url_for('rmahasiswa.akunmahasiswa')}}">Dasboard</a>
                            </li>
                            <li class="list-group-item"><a href="{{url_for('rmahasiswa.pengaduan')}}">Pengaduan</a></li>
                            <li class="list-group-item"><a href="{{url_for('rmahasiswa.pendataansurat')}}">Pendataan
                                    Surat</a>
                            </li>
                        </ul>
                        <div class="card-body">
                            <a href="{{url_for('rmahasiswa.edit_mahasiswa')}}" class="card-link">Update Profil</a>
                            <a href="{{url_for('rmahasiswa.logout_mahasiswa')}}" class="card-link">Logout</a>
                        </div>
                    </div>
                    {% else %}
                    <h1>Menu Lain</h1>
                    <li>Data Mahasiswa</li>
                    <li>Data Dosen</li>
                    {% endif %}

                </div>
            </div>
        </div>



    </div>


</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
    integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
    crossorigin="anonymous"></script>
<script src="{{ url_for ('static', filename='css/bootstrap.min.js')}}"
    integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
    crossorigin="anonymous"></script>

</html>

sim/templates/home.html
{% extends "base.html" %}

{% block konten%}

<div class="jumbotron">
    <h1 class="display-4">Hello, Selamat datang di Website saya</h1>
    <p class="lead">Ini adalah website yang pertama kali saya buat yaitu tentang pendataan Surat Masuk dan Keluar,
        website ini saya buat atas bimbingan dari dosen saya yaitu Ibu Gamaria Mandar, selaku Dosen Program studi</p>
    <hr class="my-4">
    <p>Jika terdapat kesalahan dari website saya, saya mohon maaf. saya akan kembangkan lagi website saya ini.
        terimakasih</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>
{% endblock %}

sim/templates/login_mahasiswa.html
{% extends "base.html" %}

{% block konten%}
<h1>Login Mahasiswa</h1>
<form method="POST">
    {{form.hidden_tag()}}
    <div class="form-group">
        {{form.npm.label(class="form-control-label")}}
        {% if form.npm.errors %}
        {{form.npm(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {% for error in form.npm.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {%else%}

        {{form.npm(class="form-control")}}

        {%endif%}

    </div>
    <br>

    <div class="form-group">
        {{form.password.label(class="form-control-label")}}
        {% if form.password.errors %}
        {{form.password(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {% for error in form.password.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {%else%}

        {{form.password(class="form-control")}}

        {%endif%}

    </div>

    <br>
    <div class="form-group">
        {{form.submit(class="btn btn-primary")}}
    </div>
    <br>
    <span> <a href="{{url_for('rmahasiswa.data_mhswa')}}">Daftar Akun</a></span>
</form>

{% endblock %}

sim/templates/pendataansurat.html
{% extends "base.html" %}

{% block konten%}

<div class="jumbotron">
    <br>

    <h3>Pendataan Surat Masuk dan Keluar</h3>
    <br>
    <!--form pengaduan-->
    <form method="POST">
        {{form.hidden_tag()}}
        <div class="form-group">
            {{form.nomor_surat.label(class="form-control-label")}}
            {% if form.nomor_surat.errors %}
            {{form.nomor_surat(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.nomor_surat.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {%else%}

            {{form.nomor_surat(class="form-control")}}

            {%endif%}

        </div>
        <br>
        <div class="form-group">
            {{form.jenis_surat.label(class="form-control-label")}}
            {% if form.jenis_surat.errors %}
            {{form.jenis_surat(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.jenis_surat.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {%else%}

            {{form.jenis_surat(class="form-control")}}

            {%endif%}

        </div>
        <br>
        <div class="form-group">
            {{form.perihal.label(class="form-control-label")}}
            {% if form.perihal.errors %}
            {{form.perihal(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.perihal.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {%else%}

            {{form.perihal(class="form-control")}}

            {%endif%}

        </div>
        <br>
        <div class="form-group">
            {{form.sifat_surat.label(class="form-control-label")}}
            {% if form.sifat_surat.errors %}
            {{form.sifat_surat(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.sifat_surat.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {%else%}

            {{form.sifat_surat(class="form-control")}}

            {%endif%}

        </div>
        <br>
        <div class="form-group">
            {{form.nama_instansi.label(class="form-control-label")}}
            {% if form.nama_instansi.errors %}
            {{form.nama_instansi(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.nama_instansi.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {%else%}

            {{form.nama_instansi(class="form-control")}}

            {%endif%}

        </div>
        <br>

        <div class="form-group">
            {{form.submit(class="btn btn-primary")}}
        </div>
    </form>

    <script>
        function klik_hapus(value) {
            let valid_link = document.getElementById('del-hapus')
            valid_link.href = "/delete/" + value
        }
    </script>

    <hr class="my-4">
    <h4>Data Surat Masuk dan Keluar</h4>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Tgl</th>
                    <th scope="col">nomor_surat</th>
                    <th scope="col">jenis_surat</th>
                    <th scope="col">perihal</th>
                    <th scope="col">sifat_surat</th>
                    <th scope="col">nama_instansi</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Hapus</th>
                </tr>
            </thead>
            <tbody>
                {% for data in dt_pendataansurat %}
                <tr>
                    <th><a href="{{url_for('rmahasiswa.detail_surat', ed_id=data.id)}}"><svg
                                xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-arrow-up-left-square-fill" viewBox="0 0 16 16">
                                <path
                                    d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm8.096 10.803L6 6.707v2.768a.5.5 0 0 1-1 0V5.5a.5.5 0 0 1 .5-.5h3.975a.5.5 0 1 1 0 1H6.707l4.096 4.096a.5.5 0 1 1-.707.707z" />
                            </svg></a></th>
                    <td>{{data.tgl_post}}</td>
                    <td>{{data.nomor_surat}}</td>
                    <td>{{data.jenis_surat}}</td>
                    <td>{{data.perihal}}</td>
                    <td>{{data.sifat_surat}}</td>
                    <td>{{data.nama_instansi}}</td>
                    <td><a class="btn btn-primary"
                            href="{{url_for('rmahasiswa.update_pendataansurat', ed_id=data.id)}}">Edit</a> </td>
                    <td><a class="btn btn-danger" href="/deletep/{{data.id}}"
                            onclick="return confirm('Yakin Data Mau di Hapus?')">Hapus</a></td>
                    {% endfor %}
                    <!--modals hapus-->
                    <div class="modal" tabindex="-1" role="dialog" id=modals-hapus>
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Modal title</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p>Modal body text goes here.</p>
                                </div>
                                <div class="modal-footer">
                                    <form action="">
                                        <a class="btn btn-danger" id="del-hapus">Hapus</a>
                                    </form>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

sim/templates/pengaduan.html
{% extends "base.html" %}

{% block konten%}

<div class="jumbotron">
    <br>

    <h3>Pengaduan</h3>
    <!--form pengaduan-->
    <form method="POST">
        {{form.hidden_tag()}}
        <div class="form-group">
            {{form.subjek.label(class="form-control-label")}}
            {% if form.subjek.errors %}
            {{form.subjek(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.subjek.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {%else%}

            {{form.subjek(class="form-control")}}

            {%endif%}

        </div>
        <br>
        <div class="form-group">
            {{form.kategori.label(class="form-control-label")}}
            {% if form.kategori.errors %}
            {{form.kategori(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.kategori.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {%else%}

            {{form.kategori(class="form-control")}}

            {%endif%}

        </div>
        <br>
        <div class="form-group">
            {{form.detail_pengaduan.label(class="form-control-label")}}
            {% if form.detail_pengaduan.errors %}
            {{form.detail_pengaduan(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.detail_pengaduan.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {%else%}

            {{form.detail_pengaduan(class="form-control")}}

            {%endif%}

        </div>
        <br>


        <div class="form-group">
            {{form.submit(class="btn btn-primary")}}
        </div>
    </form>

    <script>
        function klik_hapus(value) {
            let valid_link = document.getElementById('del-hapus')
            valid_link.href = "/delete/" + value
        }
    </script>

    <hr class="my-4">
    <h4>Data Pengaduan</h4>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Tgl</th>
                    <th scope="col">Subjek</th>
                    <th scope="col">Kategori</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Hapus</th>
                </tr>
            </thead>
            <tbody>
                {% for data in dt_pengaduan %}
                <tr>
                    <th><a href="{{url_for('rmahasiswa.detail_pengaduan', ed_id=data.id)}}"><svg
                                xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-arrow-up-left-square-fill" viewBox="0 0 16 16">
                                <path
                                    d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm8.096 10.803L6 6.707v2.768a.5.5 0 0 1-1 0V5.5a.5.5 0 0 1 .5-.5h3.975a.5.5 0 1 1 0 1H6.707l4.096 4.096a.5.5 0 1 1-.707.707z" />
                            </svg></a></th>
                    <td>{{data.tgl_post}}</td>
                    <td>{{data.subjek}}</td>
                    <td>{{data.kategori}}</td>
                    <td><a class="btn btn-primary"
                            href="{{url_for('rmahasiswa.update_pengaduan', ed_id=data.id)}}">Edit</a> </td>
                    <td><a class="btn btn-danger" href="/delete/{{data.id}}"
                            onclick="return confirm('Yakin Data Mau di Hapus?')">Hapus</a></td>
                    {% endfor %}
                    <!--modals hapus-->
                    <div class="modal" tabindex="-1" role="dialog" id=modals-hapus>
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Modal title</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p>Modal body text goes here.</p>
                                </div>
                                <div class="modal-footer">
                                    <form action="">
                                        <a class="btn btn-danger" id="del-hapus">Hapus</a>
                                    </form>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}